# config_uav.yml
# Config file for UAV production
mounts:
  - name: "image"
    path: "/mnt/UAV"
    host: "DiGiTS-Dev-Box-Fish.shore.mbari.org"
    nginx_root: "/UAV"

plugins:
  - name: "extractor"
    module: "aidata.plugins.extractors.tap_uav_media"
    function: "extract_media"

tator:
  project: "901902-uavs"
  host: "mantis.shore.mbari.org"
  image:
    attributes:
      iso_datetime:
        type: string
      latitude:
        type: float
      longitude:
        type: float
  box:
    attributes:
      Label:
        type: string
      score:
        type: float
      cluster:
        type: string
      saliency:
        type: float
      area:
        type: int
